#!/bin/bash

### BEGIN INIT INFO
# Provides:          dasbit
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: A Python-based IRC bot
# Description:       A Python-based IRC bot
### END INIT INFO

# This should be the location of the executable
# and the data path.
# You'll probably need to change these
DASBIT_BIN="/opt/dasbit/bin/dasbit"
DASBIT_DATA="/opt/dasbit/data"

# Shouldn't need to change these, but you can if you like
NAME="dasbit"
PIDFILE="/var/run/$NAME.pid"
LOGFILE="/var/log/$NAME.log"

# Check the executable exists
test -x $DASBIT_BIN || { echo "$DASBIT_BIN not installed or found";
  if [ "$1" = "stop" ]; then
    exit 0;
  else
    exit 5;
  fi;
}

start() {
  if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    echo "Service already running" >&2
    return 1
  fi

  echo "Starting service..." >&2
  CMD="$DASBIT_BIN $DASBIT_DATA"
  $CMD &> $LOGFILE &
  PID=$!
  echo $PID > $PIDFILE
  echo "Service started" >&2
}

stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo "Service not running" >&2
    return 1
  fi
  echo "Stopping service..." >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo "Service stopped" >&2
}

status() {
  if [ ! -f "$PIDFILE" ]; then
    echo "Service is not running" >&2
    return 1
  fi
  if kill -0 $(cat $PIDFILE); then
    echo "Service is running" >&2
    return 0
  else
    echo "Service is not running, but PID file was found"
    return 1
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac

